platform :ios, '9.0'

target 'AutoCar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AutoCar
  pod 'Alamofire'

  target 'AutoCarTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
